//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinicApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.TreatmentСase = new HashSet<TreatmentСase>();
        }
    
        public int PetId { get; set; }
        public string Name { get; set; }
        public int Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Species { get; set; }
        public string BreedType { get; set; }
        public string Colour { get; set; }
        public Nullable<int> OwnerID { get; set; }
    
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentСase> TreatmentСase { get; set; }
    }
}
